// Register-mapped HLSL reconstructed from this material's preserved FXO template.
// RGB colour clamps lift only with Juiced FP16 active (c223.x); scalar masks stay native.
float4 c0:register(c0);
float4 c2:register(c2);
float4 c4:register(c4);
float4 c8:register(c8);
float4 c24:register(c24);
float4 c25:register(c25);
float4 c26:register(c26);
float4 c27:register(c27);
float4 c28:register(c28);
float4 c29:register(c29);
float4 JuicedColour:register(c223);
sampler2D s0:register(s0);
sampler2D s1:register(s1);
sampler2D s2:register(s2);
sampler2D s3:register(s3);
float4 Select4(float4 t,float4 a,float4 b) { return float4(t.x>=0?a.x:b.x,t.y>=0?a.y:b.y,t.z>=0?a.z:b.z,t.w>=0?a.w:b.w); }
struct Inputs {
    float4 v0:TEXCOORD0;
    float4 v1:TEXCOORD1;
    float4 v2:TEXCOORD2;
    float4 v3:TEXCOORD3;
};
float4 PS_Main(Inputs input):COLOR0 {
    float4 v0=input.v0;
    float4 v1=input.v1;
    float4 v2=input.v2;
    float4 v3=input.v3;
    const float4 c1=float4(1.0,0.5,0.0,16.0);
    const float4 c3=float4(2.0,-1.0,-2.0,1.0);
    const float4 c5=float4(0.00100000005,0.0,0.0,0.0);
    float4 r0=0;
    float4 r1=0;
    float4 r2=0;
    float4 r3=0;
    float4 r4=0;
    float4 colour=0;
    r0=(tex2D(s0,(v0.xyzw).xy)).xyzw;
    colour.w=((r0.wwww*c24.wwww)).w;
    r1.xy=((-c28.yzzw+c28.zwzw)).xy;
    r0.w=((1/r1.xxxx)).w;
    r1.x=((r1.yyyy*r0.wwww)).x;
    r1.y=((c28.wwww+c28.zzzz)).y;
    r2.xyz=(c1.xyzw).xyz;
    r1.y=((r1.yyyy*-r2.yyyy+c8.yyyy)).y;
    r0.w=((r0.wwww*r1.yyyy)).w;
    r0.w=(saturate((r1.xxxx*-c1.yyyy+abs(r0.wwww)))).w;
    r1.x=((r0.wwww*c3.zzzz+c3.wwww)).x;
    r0.w=((c29.yyyy*r1.xxxx+r0.wwww)).w;
    r1.xyz=((r0.wwww*c26.xyzw)).xyz;
    r3=(tex2D(s1,(v0.xyzw).xy)).xyzw;
    r1.xyz=((r1.xyzw*r3.xyzw)).xyz;
    r0.w=((-c29.zzzz+c29.xxxx)).w;
    r1.xyz=(Select4(r0.wwww,r1.xyzw,c1.zzzz)).xyz;
    r0.xyz=((JuicedColour.x>.5 ? max((r0.xyzw*c24.xyzw+r1.xyzw),0) : saturate((r0.xyzw*c24.xyzw+r1.xyzw)))).xyz;
    r1.xyz=(max(r0.xyzw,c5.xxxx)).xyz;
    r0.x=((1/r1.xxxx)).x;
    r0.y=((1/r1.yyyy)).y;
    r0.z=((1/r1.zzzz)).z;
    r0.xyz=((r0.xyzw*c2.xyzw)).xyz;
    r1=(tex2D(s3,(v0.xyzw).xy)).xyzw;
    r1.xyz=((r1.xyzw+-c1.xxxx)).xyz;
    r1.xyz=((c25.yyyy*r1.xyzw+r2.xxxx)).xyz;
    r1.xyz=((r1.xyzw*c27.xyzw)).xyz;
    r0.xyz=((r0.xyzw*r1.xyzw)).xyz;
    r1=(tex2Dlod(s2,c1.yyzw)).xyzw;
    r0.w=((r1.wwww+-c1.xxxx)).w;
    r1=(tex2D(s2,(v0.xyzw).xy)).xyzw;
    r1.xy=(Select4(-abs(r0.wwww),r1.xyzw,r1.ywzw)).xy;
    r1.zw=((r1.xyxy*c3.xxxx+c3.yyyy)).zw;
    r3.xy=((r1.xyzw+r1.xyzw)).xy;
    r0.w=(float4(dot((r1.zwzw).xy,(-r1.zwzw).xy)+(c1.xxxx).x,dot((r1.zwzw).xy,(-r1.zwzw).xy)+(c1.xxxx).x,dot((r1.zwzw).xy,(-r1.zwzw).xy)+(c1.xxxx).x,dot((r1.zwzw).xy,(-r1.zwzw).xy)+(c1.xxxx).x)).w;
    r0.w=(rsqrt(abs(r0.wwww))).w;
    r3.z=((1/r0.wwww)).z;
    r1.xyz=((r3.xyzw+-c1.xxxx)).xyz;
    r1.xyz=((c28.xxxx*r1.xyzw+r2.zzxw)).xyz;
    r3.xyz=(float4(normalize((r1.xyzw).xyz),0)).xyz;
    r0.w=(float4(dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz))).w;
    r0.w=(rsqrt(abs(r0.wwww))).w;
    r1.x=(float4(dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz))).x;
    r1.x=(rsqrt(abs(r1.xxxx))).x;
    r1.yzw=((r1.xxxx*v1.xxyz)).yzw;
    r1.x=((1/r1.xxxx)).x;
    r1.x=((r1.xxxx+-c0.xxxx)).x;
    r1.x=(saturate((r1.xxxx*-c0.yyyy+r2.xxxx))).x;
    r2.yzw=((v3.xxyz*r0.wwww+r1.xyzw)).yzw;
    r4.xyz=(float4(normalize((r2.yzww).xyz),0)).xyz;
    r0.w=(float4(dot((r3.xyzw).xyz,(r4.xyzw).xyz),dot((r3.xyzw).xyz,(r4.xyzw).xyz),dot((r3.xyzw).xyz,(r4.xyzw).xyz),dot((r3.xyzw).xyz,(r4.xyzw).xyz))).w;
    r2.y=(float4(dot((r3.xyzw).xyz,(r1.yzww).xyz),dot((r3.xyzw).xyz,(r1.yzww).xyz),dot((r3.xyzw).xyz,(r1.yzww).xyz),dot((r3.xyzw).xyz,(r1.yzww).xyz))).y;
    r2.z=(max(r0.wwww,c1.zzzz)).z;
    r0.w=(pow(abs(r2.zzzz),c25.zzzz)).w;
    r0.w=((r0.wwww*c25.wwww)).w;
    r0.xyz=((r0.xyzw*r0.wwww+c2.xyzw)).xyz;
    r3.xyz=(float4(normalize((v2.xyzw).xyz),0)).xyz;
    r0.w=(float4(dot((r1.yzww).xyz,(r3.xyzw).xyz),dot((r1.yzww).xyz,(r3.xyzw).xyz),dot((r1.yzww).xyz,(r3.xyzw).xyz),dot((r1.yzww).xyz,(r3.xyzw).xyz))).w;
    r0.w=((r0.wwww+c0.zzzz)).w;
    r0.w=(saturate((r0.wwww*c0.wwww+r2.xxxx))).w;
    r1.x=((r1.xxxx*r2.yyyy)).x;
    r0.w=((r0.wwww*r1.xxxx)).w;
    r0.w=(Select4(r2.yyyy,r0.wwww,c1.zzzz)).w;
    r0.xyz=((r0.wwww*r0.xyzw)).xyz;
    r0.w=((1/c4.yyyy)).w;
    colour.xyz=((r0.xyzw*r0.wwww)).xyz;
    return colour;
}
