// Register-mapped HLSL reconstructed from this material's preserved FXO template.
// RGB colour clamps lift only with Juiced FP16 active (c223.x); scalar masks stay native.
float4 c9:register(c9);
float4 c25:register(c25);
float4 c26:register(c26);
float4 c27:register(c27);
float4 c28:register(c28);
float4 c29:register(c29);
float4 c30:register(c30);
float4 c31:register(c31);
float4 c32:register(c32);
float4 c33:register(c33);
float4 JuicedColour:register(c223);
sampler2D s0:register(s0);
sampler2D s1:register(s1);
sampler2D s2:register(s2);
float4 Select4(float4 t,float4 a,float4 b) { return float4(t.x>=0?a.x:b.x,t.y>=0?a.y:b.y,t.z>=0?a.z:b.z,t.w>=0?a.w:b.w); }
struct Inputs {
    float4 v0:TEXCOORD0;
    float4 v1:TEXCOORD1;
    float4 v2:TEXCOORD2;
    float4 v3:TEXCOORD3;
    float4 v4:TEXCOORD4;
    float4 v5:TEXCOORD5;
};
float4 PS_Main(Inputs input):COLOR0 {
    float4 v0=input.v0;
    float4 v1=input.v1;
    float4 v2=input.v2;
    float4 v3=input.v3;
    float4 v4=input.v4;
    float4 v5=input.v5;
    const float4 c0=float4(0.5,0.0,16.0,-1.0);
    const float4 c1=float4(2.0,-1.0,100.0,0.150000006);
    const float4 c2=float4(0.300000012,0.589999974,0.109999999,0.0);
    const float4 c3=float4(0.5,-0.5,0.0,0.0);
    float4 r0=0;
    float4 r1=0;
    float4 r2=0;
    float4 r3=0;
    float4 r4=0;
    float4 r5=0;
    float4 r6=0;
    float4 colour=0;
    r0=(tex2D(s0,(v0.zwzw).xy)).xyzw;
    r1=(tex2Dlod(s0,c0.xxyz)).xyzw;
    r0.z=((r1.wwww+c0.wwww)).z;
    r0.xy=(Select4(-abs(r0.zzzz),r0.xyzw,r0.ywzw)).xy;
    r1.xy=((r0.xyzw*c1.xxxx+c1.yyyy)).xy;
    r2.xy=((r0.xyzw+r0.xyzw)).xy;
    r0.x=(float4(dot((r1.xyzw).xy,(-r1.xyzw).xy)+(-c0.wwww).x,dot((r1.xyzw).xy,(-r1.xyzw).xy)+(-c0.wwww).x,dot((r1.xyzw).xy,(-r1.xyzw).xy)+(-c0.wwww).x,dot((r1.xyzw).xy,(-r1.xyzw).xy)+(-c0.wwww).x)).x;
    r0.x=(rsqrt(abs(r0.xxxx))).x;
    r2.z=((1/r0.xxxx)).z;
    r0.xyw=((r2.xyzz+c0.wwww)).xyw;
    r1.yw=(c0.xyzw).yw;
    r0.xyw=((c27.wwww*r0.xyzw+abs(r1.yyzw))).xyw;
    r1.xyz=(float4(normalize((r0.xyww).xyz),0)).xyz;
    r2=(tex2D(s0,(v0.xyzw).xy)).xyzw;
    r0.xy=(Select4(-abs(r0.zzzz),r2.xyzw,r2.ywzw)).xy;
    r0.zw=((r0.xyxy*c1.xxxx+c1.yyyy)).zw;
    r2.xy=((r0.xyzw+r0.xyzw)).xy;
    r0.x=(float4(dot((r0.zwzw).xy,(-r0.zwzw).xy)+(-c0.wwww).x,dot((r0.zwzw).xy,(-r0.zwzw).xy)+(-c0.wwww).x,dot((r0.zwzw).xy,(-r0.zwzw).xy)+(-c0.wwww).x,dot((r0.zwzw).xy,(-r0.zwzw).xy)+(-c0.wwww).x)).x;
    r0.x=(rsqrt(abs(r0.xxxx))).x;
    r2.z=((1/r0.xxxx)).z;
    r0.xyz=((r2.xyzw+c0.wwww)).xyz;
    r0.w=(float4(dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz))).w;
    r0.w=(rsqrt(abs(r0.wwww))).w;
    r2.x=((1/r0.wwww)).x;
    r2.y=((r2.xxxx+-c27.xxxx)).y;
    r2.xz=((r2.xxxx+-c30.xyyw)).xz;
    r2.xz=(saturate((r2.xyzw*c30.zyww))).xz;
    r2.y=(saturate((r2.yyyy*c27.yyyy))).y;
    r2.y=((-r2.yyyy+-c0.wwww)).y;
    r2.y=((r2.yyyy*c27.zzzz)).y;
    r0.xyz=((r2.yyyy*r0.xyzw+abs(c0.yyww))).xyz;
    r2.y=(float4(dot((r0.xyzw).xyz,(r0.xyzw).xyz),dot((r0.xyzw).xyz,(r0.xyzw).xyz),dot((r0.xyzw).xyz,(r0.xyzw).xyz),dot((r0.xyzw).xyz,(r0.xyzw).xyz))).y;
    r2.y=(rsqrt(abs(r2.yyyy))).y;
    r0.xyz=((r0.xyzw*r2.yyyy+r1.xyzw)).xyz;
    r1.xyz=(float4(normalize((r0.xyzw).xyz),0)).xyz;
    r0.x=(float4(dot((v2.xyzw).xyz,(v2.xyzw).xyz),dot((v2.xyzw).xyz,(v2.xyzw).xyz),dot((v2.xyzw).xyz,(v2.xyzw).xyz),dot((v2.xyzw).xyz,(v2.xyzw).xyz))).x;
    r0.x=(rsqrt(abs(r0.xxxx))).x;
    r3.xyz=((r0.wwww*v3.xyzw)).xyz;
    r0.y=(saturate((r0.wwww*c1.zzzz))).y;
    r0.xzw=((v2.xyyz*r0.xxxx+r3.xyyz)).xzw;
    r4.xyz=(float4(normalize((r0.xzww).xyz),0)).xyz;
    r0.x=(float4(dot((r1.xyzw).xyz,(r4.xyzw).xyz),dot((r1.xyzw).xyz,(r4.xyzw).xyz),dot((r1.xyzw).xyz,(r4.xyzw).xyz),dot((r1.xyzw).xyz,(r4.xyzw).xyz))).x;
    r2.y=(max(r0.xxxx,c0.yyyy)).y;
    r0.x=(pow(abs(r2.yyyy),c26.xxxx)).x;
    r0.z=(saturate(float4(dot((r3.xyzw).xyz,(r1.xyzw).xyz),dot((r3.xyzw).xyz,(r1.xyzw).xyz),dot((r3.xyzw).xyz,(r1.xyzw).xyz),dot((r3.xyzw).xyz,(r1.xyzw).xyz)))).z;
    r0.z=((-r0.zzzz+-c0.wwww)).z;
    r0.w=((r0.zzzz*r0.zzzz)).w;
    r0.z=((r0.wwww*r0.zzzz)).z;
    r2.y=(lerp(c31.xxxx,-r1.wwww,r0.zzzz)).y;
    r0.z=((r2.yyyy*c26.yyyy)).z;
    r0.x=((r0.zzzz*r0.xxxx)).x;
    r4=(c25.xyzw).xyzw;
    r5.xyz=((r4.xyzw*c33.xyzw)).xyz;
    r5.xyz=((r0.xxxx*r5.xyzw)).xyz;
    r4=((r4.xyzw*c32.xyzw)).xyzw;
    r5.xyz=((r4.wwww*r5.xyzw)).xyz;
    r0.x=(float4(dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz))).x;
    r0.x=(rsqrt(abs(r0.xxxx))).x;
    r3.xyz=((v1.xyzw*r0.xxxx+r3.xyzw)).xyz;
    r6.xyz=(float4(normalize((r3.xyzw).xyz),0)).xyz;
    r0.x=(float4(dot((r1.xyzw).xyz,(r6.xyzw).xyz),dot((r1.xyzw).xyz,(r6.xyzw).xyz),dot((r1.xyzw).xyz,(r6.xyzw).xyz),dot((r1.xyzw).xyz,(r6.xyzw).xyz))).x;
    r1.xy=((r1.yxzw*c31.yyyy)).xy;
    r1.xy=((r1.xyzw*c9.wzzw)).xy;
    r0.yw=((r0.yyyy*r1.xxzy)).yw;
    r1.x=(max(r0.xxxx,c0.yyyy)).x;
    r0.x=(pow(abs(r1.xxxx),c26.xxxx)).x;
    r0.x=((r0.xxxx*r0.zzzz)).x;
    r1.xyz=((r0.xxxx*r4.xyzw)).xyz;
    r1.xyz=((JuicedColour.x>.5 ? max((r1.xyzw*r4.wwww+r5.xyzw),0) : saturate((r1.xyzw*r4.wwww+r5.xyzw)))).xyz;
    r0.x=((1/v4.wwww)).x;
    r3.xy=((r0.xxxx*v4.xyzw)).xy;
    r0.x=((v4.zzzz*-r0.xxxx+-c0.wwww)).x;
    r0.x=((1/r0.xxxx)).x;
    r0.x=((r0.xxxx*c1.wwww)).x;
    r3.xy=((r3.xyzw*c3.xyzw+c3.xxxx)).xy;
    r3=(tex2D(s1,(r3.xyzw).xy)).xyzw;
    r0.z=((-r3.xxxx+-c0.wwww)).z;
    r0.z=((1/r0.zzzz)).z;
    r0.x=((r0.zzzz*c1.wwww+-r0.xxxx)).x;
    r0.z=((1/c26.zzzz)).z;
    r0.z=(saturate((r0.zzzz*abs(r0.xxxx)))).z;
    r1.w=((1/v5.wwww)).w;
    r3.xy=((r1.wwww*v5.xyzw)).xy;
    r1.w=((r3.xxxx*c0.xxxx+c0.xxxx)).w;
    r2.w=((r3.yyyy*c0.xxxx)).w;
    r0.y=((r0.yyyy*r0.zzzz+-r2.wwww)).y;
    r0.z=((r0.wwww*r0.zzzz+-r1.wwww)).z;
    r3.x=((r0.zzzz+-c0.wwww)).x;
    r3.y=((r0.yyyy+c0.xxxx)).y;
    r3=(tex2D(s2,(r3.xyzw).xy)).xyzw;
    r0.y=((-r3.wwww+-c0.wwww)).y;
    r0.yzw=((r0.yyyy*r1.xxyz)).yzw;
    r1.w=(c28.wwww).w;
    r1.x=((-r1.wwww+c29.wwww)).x;
    r1.x=((r2.zzzz*r1.xxxx+c28.wwww)).x;
    r1.x=((r1.xxxx*-r2.xxxx+-c0.wwww)).x;
    r0.yzw=((r0.xyzw*r1.xxxx)).yzw;
    r0.yzw=((r3.xxyz*r2.yyyy+r0.xyzw)).yzw;
    r0.y=(float4(dot((r0.yzww).xyz,(c2.xyzw).xyz),dot((r0.yzww).xyz,(c2.xyzw).xyz),dot((r0.yzww).xyz,(c2.xyzw).xyz),dot((r0.yzww).xyz,(c2.xyzw).xyz))).y;
    r0.z=((1/c26.wwww)).z;
    r0.x=(saturate((r0.zzzz*abs(r0.xxxx)))).x;
    r0.z=((-r0.xxxx+-c0.wwww)).z;
    colour.w=((r0.yyyy*r0.zzzz+r0.xxxx)).w;
    colour.xyz=(c0.yyyy).xyz;
    return colour;
}
