// Register-mapped HLSL reconstructed from this material's preserved FXO template.
// RGB colour clamps lift only with Juiced FP16 active (c223.x); scalar masks stay native.
float4 c0:register(c0);
float4 c2:register(c2);
float4 c4:register(c4);
float4 c8:register(c8);
float4 c24:register(c24);
float4 c25:register(c25);
float4 c26:register(c26);
float4 c27:register(c27);
float4 c28:register(c28);
float4 c29:register(c29);
float4 JuicedColour:register(c223);
sampler2D s0:register(s0);
sampler2D s1:register(s1);
sampler2D s2:register(s2);
sampler2D s3:register(s3);
float4 Select4(float4 t,float4 a,float4 b) { return float4(t.x>=0?a.x:b.x,t.y>=0?a.y:b.y,t.z>=0?a.z:b.z,t.w>=0?a.w:b.w); }
struct Inputs {
    float4 v0:TEXCOORD0;
    float4 v1:TEXCOORD1;
    float4 v2:TEXCOORD2;
    float4 v3:TEXCOORD3;
};
float4 PS_Main(Inputs input):COLOR0 {
    float4 v0=input.v0;
    float4 v1=input.v1;
    float4 v2=input.v2;
    float4 v3=input.v3;
    const float4 c1=float4(0.5,0.0,16.0,-1.0);
    const float4 c3=float4(2.0,-1.0,-2.0,1.0);
    const float4 c5=float4(0.00100000005,0.0,0.0,0.0);
    float4 r0=0;
    float4 r1=0;
    float4 r2=0;
    float4 r3=0;
    float4 colour=0;
    r0.x=(float4(dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz),dot((v1.xyzw).xyz,(v1.xyzw).xyz))).x;
    r0.x=(rsqrt(abs(r0.xxxx))).x;
    r0.y=((1/r0.xxxx)).y;
    r0.xzw=((r0.xxxx*v1.xyyz)).xzw;
    r0.y=((r0.yyyy+-c0.xxxx)).y;
    r1.xyw=(c1.xyzw).xyw;
    r0.y=(saturate((r0.yyyy*-c0.yyyy+-r1.wwww))).y;
    r2=(tex2Dlod(s2,c1.xxyz)).xyzw;
    r1.z=((r2.wwww+c1.wwww)).z;
    r2=(tex2D(s2,(v0.xyzw).xy)).xyzw;
    r2.xy=(Select4(-abs(r1.zzzz),r2.xyzw,r2.ywzw)).xy;
    r2.zw=((r2.xyxy*c3.xxxx+c3.yyyy)).zw;
    r3.xy=((r2.xyzw+r2.xyzw)).xy;
    r1.z=(float4(dot((r2.zwzw).xy,(-r2.zwzw).xy)+(-c1.wwww).x,dot((r2.zwzw).xy,(-r2.zwzw).xy)+(-c1.wwww).x,dot((r2.zwzw).xy,(-r2.zwzw).xy)+(-c1.wwww).x,dot((r2.zwzw).xy,(-r2.zwzw).xy)+(-c1.wwww).x)).z;
    r1.z=(rsqrt(abs(r1.zzzz))).z;
    r3.z=((1/r1.zzzz)).z;
    r2.xyz=((r3.xyzw+c1.wwww)).xyz;
    r2.xyz=((c28.xxxx*r2.xyzw+abs(r1.yyww))).xyz;
    r3.xyz=(float4(normalize((r2.xyzw).xyz),0)).xyz;
    r1.y=(float4(dot((r3.xyzw).xyz,(r0.xzww).xyz),dot((r3.xyzw).xyz,(r0.xzww).xyz),dot((r3.xyzw).xyz,(r0.xzww).xyz),dot((r3.xyzw).xyz,(r0.xzww).xyz))).y;
    r0.y=((r0.yyyy*r1.yyyy)).y;
    r2.xyz=(float4(normalize((v2.xyzw).xyz),0)).xyz;
    r1.z=(float4(dot((r0.xzww).xyz,(r2.xyzw).xyz),dot((r0.xzww).xyz,(r2.xyzw).xyz),dot((r0.xzww).xyz,(r2.xyzw).xyz),dot((r0.xzww).xyz,(r2.xyzw).xyz))).z;
    r1.z=((r1.zzzz+c0.zzzz)).z;
    r1.z=(saturate((r1.zzzz*c0.wwww+-r1.wwww))).z;
    r0.y=((r0.yyyy*r1.zzzz)).y;
    r0.y=(Select4(r1.yyyy,r0.yyyy,c1.yyyy)).y;
    r1.y=(float4(dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz),dot((v3.xyzw).xyz,(v3.xyzw).xyz))).y;
    r1.y=(rsqrt(abs(r1.yyyy))).y;
    r0.xzw=((v3.xyyz*r1.yyyy+r0.xyzw)).xzw;
    r2.xyz=(float4(normalize((r0.xzww).xyz),0)).xyz;
    r0.x=(float4(dot((r3.xyzw).xyz,(r2.xyzw).xyz),dot((r3.xyzw).xyz,(r2.xyzw).xyz),dot((r3.xyzw).xyz,(r2.xyzw).xyz),dot((r3.xyzw).xyz,(r2.xyzw).xyz))).x;
    r1.y=(max(r0.xxxx,c1.yyyy)).y;
    r0.x=(pow(abs(r1.yyyy),c25.zzzz)).x;
    r0.x=((r0.xxxx*c25.wwww)).x;
    r0.zw=((c28.xyzw+-c28.xyyz)).zw;
    r0.z=((1/r0.zzzz)).z;
    r0.w=((r0.zzzz*r0.wwww)).w;
    r1.y=((c28.zzzz+c28.wwww)).y;
    r1.x=((r1.yyyy*-r1.xxxx+c8.yyyy)).x;
    r0.z=((r0.zzzz*r1.xxxx)).z;
    r0.z=(saturate((r0.wwww*-c1.xxxx+abs(r0.zzzz)))).z;
    r0.w=((r0.zzzz*c3.zzzz+c3.wwww)).w;
    r0.z=((c29.yyyy*r0.wwww+r0.zzzz)).z;
    r1.xyz=((r0.zzzz*c26.xyzw)).xyz;
    r2=(tex2D(s1,(v0.zwzw).xy)).xyzw;
    r1.xyz=((r1.xyzw*r2.xyzw)).xyz;
    r0.z=((c29.xxxx+-c29.zzzz)).z;
    r1.xyz=(Select4(r0.zzzz,r1.xyzw,c1.yyyy)).xyz;
    r2=(tex2D(s0,(v0.xyzw).xy)).xyzw;
    r1.xyz=((JuicedColour.x>.5 ? max((r2.xyzw*c24.xyzw+r1.xyzw),0) : saturate((r2.xyzw*c24.xyzw+r1.xyzw)))).xyz;
    r0.z=((r2.wwww*c24.wwww)).z;
    colour.w=(r0.zzzz).w;
    r2.xyz=(max(r1.xyzw,c5.xxxx)).xyz;
    r1.x=((1/r2.xxxx)).x;
    r1.y=((1/r2.yyyy)).y;
    r1.z=((1/r2.zzzz)).z;
    r1.xyz=((r1.xyzw*c2.xyzw)).xyz;
    r2=(tex2D(s3,(v0.xyzw).xy)).xyzw;
    r2.xyz=((r2.xyzw+c1.wwww)).xyz;
    r2.xyz=((c25.yyyy*r2.xyzw+-r1.wwww)).xyz;
    r2.xyz=((r2.xyzw*c27.xyzw)).xyz;
    r1.xyz=((r1.xyzw*r2.xyzw)).xyz;
    r0.xzw=((r1.xyyz*r0.xxxx+c2.xyyz)).xzw;
    r0.xyz=((r0.xzww*r0.yyyy)).xyz;
    r0.w=((1/c4.yyyy)).w;
    colour.xyz=((r0.wwww*r0.xyzw)).xyz;
    return colour;
}
