"""Compile embedded SM3 TAA shaders with Windows' D3DCompiler; no game-time compiler."""
import ctypes as C
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Juiced Patch/Render/TemporalSR2.hlsl"
OUTPUT = ROOT / "Juiced Patch/Render/TemporalShaders.h"
ENTRIES = ["PS_CameraMotion", "PS_CopyDepth", "PS_Velocity", "PS_OpaqueLuma", "PS_CopyColor", "PS_TemporalResolve", "PS_Debug", "PS_StoreHistoryDepth"]

def blob_bytes(blob):
    v = C.cast(blob, C.POINTER(C.POINTER(C.c_void_p))).contents
    p = C.WINFUNCTYPE(C.c_void_p, C.c_void_p)(v[3])(blob)
    n = C.WINFUNCTYPE(C.c_size_t, C.c_void_p)(v[4])(blob)
    data = C.string_at(p, n)
    C.WINFUNCTYPE(C.c_ulong, C.c_void_p)(v[2])(blob)
    return data

def compile_shaders():
    dll = C.WinDLL("d3dcompiler_47.dll")
    compile_fn = dll.D3DCompile
    compile_fn.argtypes = [C.c_void_p, C.c_size_t, C.c_char_p, C.c_void_p, C.c_void_p, C.c_char_p, C.c_char_p, C.c_uint, C.c_uint, C.POINTER(C.c_void_p), C.POINTER(C.c_void_p)]
    compile_fn.restype = C.c_long
    source = SOURCE.read_bytes()
    out = ["// Generated by tools/compile_temporal.py. GPL-3.0; see TemporalSR2.hlsl.", "#pragma once", "#include <cstdint>", "namespace TemporalAA::Bytecode", "{"]
    for entry in ENTRIES:
        blob, errors = C.c_void_p(), C.c_void_p()
        hr = compile_fn(source, len(source), SOURCE.name.encode(), None, None, entry.encode(), b"ps_3_0", 1 << 15, 0, C.byref(blob), C.byref(errors))
        message = blob_bytes(errors).decode(errors="replace") if errors.value else ""
        if hr < 0:
            raise RuntimeError(entry + ": " + message)
        data = blob_bytes(blob)
        words = struct.unpack("<" + "I" * (len(data) // 4), data)
        out.append("inline constexpr uint32_t " + entry + "[] = {")
        for i in range(0, len(words), 8):
            out.append("    " + ", ".join(f"0x{x:08X}u" for x in words[i:i+8]) + ",")
        out.append("};")
        print(f"{entry}: {len(words)} DWORDs")
    out.append("}")
    OUTPUT.write_text("\n".join(out) + "\n", encoding="utf-8")

if __name__ == "__main__":
    compile_shaders()
